db:
  image: redis
  ports:
    - "6379:6379"
mysqlaccounts:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: user
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: test