spring:
    redis:
      host: localhost
      password:
    datasource:
           url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false
           username: user
           password: 123456
           driver-class-name: com.mysql.jdbc.Driver
           initialize: true
           jmx-enabled: true
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop